[tool.poetry]
name = "restapi-graphql-project"
version = "0.1.0"
description = ""
authors = ["Yuchen <yucpeng17@outlook.com>"]

[tool.poetry.dependencies]



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
